# Assignment 2

### Basic Manuplation with datasets

In [36]:
import pandas as pd

In [3]:
df=pd.read_csv("loan.csv")
df

NameError: name 'pd' is not defined

In [39]:
df.shape

(500, 11)

In [40]:
df.head()

Loan_ID loan_status  Principal  terms effective_date   due_date  \
0  xqd20166231     PAIDOFF       1000     30       9/8/2016  10/7/2016   
1  xqd20168902     PAIDOFF       1000     30       9/8/2016  10/7/2016   
2  xqd20160003     PAIDOFF       1000     30       9/8/2016  10/7/2016   
3  xqd20160004     PAIDOFF       1000     15       9/8/2016  9/22/2016   
4  xqd20160005     PAIDOFF       1000     30       9/9/2016  10/8/2016   

     paid_off_time  past_due_days  age             education  Gender  
0  9/14/2016 19:31            NaN   45  High School or Below    male  
1   10/7/2016 9:00            NaN   50              Bechalor  female  
2  9/25/2016 16:58            NaN   33              Bechalor  female  
3  9/22/2016 20:00            NaN   27               college    male  
4  9/23/2016 21:36            NaN   28               college  female

In [41]:
df.tail()

Loan_ID         loan_status  Principal  terms effective_date  \
495  xqd20160496  COLLECTION_PAIDOFF       1000     30      9/12/2016   
496  xqd20160497  COLLECTION_PAIDOFF       1000     15      9/12/2016   
497  xqd20160498  COLLECTION_PAIDOFF        800     15      9/12/2016   
498  xqd20160499  COLLECTION_PAIDOFF       1000     30      9/12/2016   
499  xqd20160500  COLLECTION_PAIDOFF       1000     30      9/12/2016   

       due_date     paid_off_time  past_due_days  age             education  \
495  10/11/2016  10/14/2016 19:08            3.0   28  High School or Below   
496   9/26/2016  10/10/2016 20:02           14.0   26  High School or Below   
497   9/26/2016   9/29/2016 11:49            3.0   30               college   
498  11/10/2016  11/11/2016 22:40            1.0   38               college   
499  10/11/2016  10/19/2016 11:58            8.0   28  High School or Below   

     Gender  
495    male  
496    male  
497    male  
498  female  
499    male

In [42]:
#checking for missing values
df.isnull().sum()

Loan_ID             0
loan_status         0
Principal           0
terms               0
effective_date      0
due_date            0
paid_off_time     100
past_due_days     300
age                 0
education           0
Gender              0
dtype: int64

In [43]:
df.columns#printing columns

Index(['Loan_ID', 'loan_status', 'Principal', 'terms', 'effective_date',
       'due_date', 'paid_off_time', 'past_due_days', 'age', 'education',
       'Gender'],
      dtype='object')

In [44]:
df.info()#object represents the string datatype

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 11 columns):
Loan_ID           500 non-null object
loan_status       500 non-null object
Principal         500 non-null int64
terms             500 non-null int64
effective_date    500 non-null object
due_date          500 non-null object
paid_off_time     400 non-null object
past_due_days     200 non-null float64
age               500 non-null int64
education         500 non-null object
Gender            500 non-null object
dtypes: float64(1), int64(3), object(7)
memory usage: 43.1+ KB


In [45]:
df.describe() #it describe the statistcal data std-standard deviation

Principal       terms  past_due_days         age
count   500.000000  500.000000      200.00000  500.000000
mean    943.200000   22.824000       36.01000   31.116000
std     115.240274    8.000064       29.38088    6.084784
min     300.000000    7.000000        1.00000   18.000000
25%    1000.000000   15.000000        3.00000   27.000000
50%    1000.000000   30.000000       37.00000   30.000000
75%    1000.000000   30.000000       60.00000   35.000000
max    1000.000000   30.000000       76.00000   51.000000

In [47]:
#check for unique values in  
df.education.unique()

array(['High School or Below', 'Bechalor', 'college', 'Master or Above'],
      dtype=object)

In [48]:
#check for duplicates
df.duplicated().sum()

0

### Numpy manuplations

In [49]:
import numpy as np

In [50]:
#1D array
a=np.array([1,2,3])
print(a)

[1 2 3]


In [51]:
#2D array
a=np.array([(1,2,3),(4,5,6)])
print(a)

[[1 2 3]
 [4 5 6]]


In [52]:
#finding the dimension of array
a = np.array([(1,2,3),(4,5,6)])
print(a.ndim)

2


In [53]:
#finding the itemsize
a = np.array([(1,2,3)])
print(a.itemsize)

4


In [54]:
#finding the particular datatype
a = np.array([(1,2,3)])
print(a.dtype)

int32


In [55]:
#finding the size and dimension of array
a = np.array([(1,2,3,4,5,6)])
print(a.size)
print(a.shape)

6
(1, 6)


In [56]:
#reshaping the dimensions
a = np.array([(8,9,10),(11,12,13)])
a=a.reshape(3,2)                   
print(a)

[[ 8  9]
 [10 11]
 [12 13]]


In [57]:
#FINDING THE MAX,MIN AND  sum
a= np.array([1,2,3])
print(a.min())
print(a.max())
print(a.sum())

1
3
6


In [58]:
#multiplications subtraction and division of two matrices
x= np.array([(1,2,3),(3,4,5)])
y= np.array([(1,2,3),(3,4,5)])
print(x-y)
print(x*y)
print(x/y)

[[0 0 0]
 [0 0 0]]
[[ 1  4  9]
 [ 9 16 25]]
[[1. 1. 1.]
 [1. 1. 1.]]
